services:
  - type: web
    name: football-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python init_db.py && gunicorn app:app
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: FOOTBALL_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: ODDS_API_KEY
        sync: false
